##   lambda function:

In [1]:
import numpy as np

In [10]:
SPN = np.random.randint(0, 100, (3, 6, 5))

In [11]:
SPN

array([[[10, 11, 80,  3, 41],
        [95, 69, 12, 48, 56],
        [27, 95, 18, 17, 94],
        [82,  8, 19, 26, 87],
        [36, 54, 34,  8, 33],
        [43, 44, 13, 30, 39]],

       [[ 5, 94,  8,  9, 20],
        [11, 60, 62,  6, 20],
        [42, 91, 70, 92, 51],
        [74, 61,  9, 99, 20],
        [40, 56, 79, 90, 76],
        [ 9, 86, 33, 52, 89]],

       [[59, 56, 77, 41, 72],
        [95, 63, 52, 63, 15],
        [17, 87, 40, 10, 42],
        [ 9, 12, 19, 61, 85],
        [87, 66, 12, 82, 49],
        [ 6,  4, 64, 44, 59]]])

In [20]:
test=lambda tr: SPN[:,0,:]

In [21]:
test

<function __main__.<lambda>(tr)>

##  tr has nothing to with SPN

In [30]:
tre=np.array([1,2,3])

In [31]:
tre

array([1, 2, 3])

In [32]:
SPN

array([[[10, 11, 80,  3, 41],
        [95, 69, 12, 48, 56],
        [27, 95, 18, 17, 94],
        [82,  8, 19, 26, 87],
        [36, 54, 34,  8, 33],
        [43, 44, 13, 30, 39]],

       [[ 5, 94,  8,  9, 20],
        [11, 60, 62,  6, 20],
        [42, 91, 70, 92, 51],
        [74, 61,  9, 99, 20],
        [40, 56, 79, 90, 76],
        [ 9, 86, 33, 52, 89]],

       [[59, 56, 77, 41, 72],
        [95, 63, 52, 63, 15],
        [17, 87, 40, 10, 42],
        [ 9, 12, 19, 61, 85],
        [87, 66, 12, 82, 49],
        [ 6,  4, 64, 44, 59]]])

In [33]:
test(tre)

array([[10, 11, 80,  3, 41],
       [ 5, 94,  8,  9, 20],
       [59, 56, 77, 41, 72]])

In [34]:
ff=0

In [35]:
test(ff)

array([[10, 11, 80,  3, 41],
       [ 5, 94,  8,  9, 20],
       [59, 56, 77, 41, 72]])

##  We get the same result